# Use root/example as user/password credentials
version: '3.8'
services:

    mongo:
      image: mongo
      restart: always
      ports:
        - 27017:27017
          
    node:
      user: node
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 3000:3000

      volumes:
        - ..:/Ito-ocashi-review:cached
        - /Ito-ocashi-review/front/node_modules
        - /Ito-ocashi-review/front/.next
        - /Ito-ocashi-review/back/node_modules
      tty: true
